package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-07-08T18:35:19.789+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://www.example.org/store/", name = "store")
@XmlSeeAlso({ObjectFactory.class})
public interface Store {

    @WebMethod(action = "http://www.example.org/store/getAllProducts")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://www.example.org/store/", className = "service.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://www.example.org/store/", className = "service.GetAllProductsResponse")
    @WebResult(name = "products", targetNamespace = "")
    public java.util.List<service.ProductType> getAllProducts(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://www.example.org/store/", className = "service.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://www.example.org/store/", className = "service.GetProductResponse")
    @WebResult(name = "product", targetNamespace = "")
    public service.ProductType getProduct(
        @WebParam(name = "idProduct", targetNamespace = "")
        int idProduct
    );

    @WebMethod
    @RequestWrapper(localName = "addTransaction", targetNamespace = "http://www.example.org/store/", className = "service.AddTransaction")
    @ResponseWrapper(localName = "addTransactionResponse", targetNamespace = "http://www.example.org/store/", className = "service.AddTransactionResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addTransaction(
        @WebParam(name = "idProduct", targetNamespace = "")
        int idProduct,
        @WebParam(name = "idUser", targetNamespace = "")
        int idUser,
        @WebParam(name = "price", targetNamespace = "")
        float price,
        @WebParam(name = "paymentSuccess", targetNamespace = "")
        boolean paymentSuccess
    );

    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://www.example.org/store/", className = "service.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://www.example.org/store/", className = "service.AddProductResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addProduct(
        @WebParam(name = "product", targetNamespace = "")
        service.ProductType product
    );

    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://www.example.org/store/", className = "service.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://www.example.org/store/", className = "service.UpdateProductResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean updateProduct(
        @WebParam(name = "product", targetNamespace = "")
        service.ProductType product
    );
}
