package bankClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-07-06T19:34:04.863+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://www.example.org/bank/", name = "bank")
@XmlSeeAlso({ObjectFactory.class})
public interface Bank {

    @WebMethod(action = "http://www.example.org/bank/addTransaction")
    @RequestWrapper(localName = "addTransaction", targetNamespace = "http://www.example.org/bank/", className = "bankClient.AddTransaction")
    @ResponseWrapper(localName = "addTransactionResponse", targetNamespace = "http://www.example.org/bank/", className = "bankClient.AddTransactionResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addTransaction(
        @WebParam(name = "payment", targetNamespace = "")
        bankClient.PaymentType payment
    );
}
