package storeClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5-jbossorg-1
 * 2019-07-08T18:39:38.416+02:00
 * Generated source version: 3.2.5-jbossorg-1
 *
 */
@WebService(targetNamespace = "http://www.example.org/store/", name = "store")
@XmlSeeAlso({ObjectFactory.class})
public interface Store {

    @WebMethod(action = "http://www.example.org/store/getAllProducts")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://www.example.org/store/", className = "storeClient.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://www.example.org/store/", className = "storeClient.GetAllProductsResponse")
    @WebResult(name = "products", targetNamespace = "")
    public java.util.List<storeClient.ProductType> getAllProducts(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod
    @RequestWrapper(localName = "addTransaction", targetNamespace = "http://www.example.org/store/", className = "storeClient.AddTransaction")
    @ResponseWrapper(localName = "addTransactionResponse", targetNamespace = "http://www.example.org/store/", className = "storeClient.AddTransactionResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addTransaction(
        @WebParam(name = "idProduct", targetNamespace = "")
        int idProduct,
        @WebParam(name = "idUser", targetNamespace = "")
        int idUser,
        @WebParam(name = "price", targetNamespace = "")
        float price,
        @WebParam(name = "paymentSuccess", targetNamespace = "")
        boolean paymentSuccess
    );

    @WebMethod
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://www.example.org/store/", className = "storeClient.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://www.example.org/store/", className = "storeClient.GetProductResponse")
    @WebResult(name = "product", targetNamespace = "")
    public storeClient.ProductType getProduct(
        @WebParam(name = "idProduct", targetNamespace = "")
        int idProduct
    );

    @WebMethod
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://www.example.org/store/", className = "storeClient.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://www.example.org/store/", className = "storeClient.AddProductResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean addProduct(
        @WebParam(name = "product", targetNamespace = "")
        storeClient.ProductType product
    );

    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://www.example.org/store/", className = "storeClient.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://www.example.org/store/", className = "storeClient.UpdateProductResponse")
    @WebResult(name = "out", targetNamespace = "")
    public boolean updateProduct(
        @WebParam(name = "product", targetNamespace = "")
        storeClient.ProductType product
    );
}
